version: '3'
services:
  aerials:
    image: declanfitzpatrick/aerials:latest
    container_name: aerials
    ports:
      - 5050:80
    volumes: 
      - ./downloads:/static/downloads
      - ./api:/static/api
      - ./index.html:/static/index.html
      - ./style.css:/static/style.css
    restart: unless-stopped