version: '3'
services:
  aerials:
    image: flashspys/nginx-static
    container_name: aerials
    ports:
      - 8080:80
    volumes: 
      - ./downloads:/static/downloads
      - ./api:/static/api
      - ./index.html:/static/index.html
      - ./style.css:/static/style.css